{% set name = "p4p" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdavidsaver/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d15ab50b84b7dc451a39087952886d1ff6626c21eaa00e80dd8823dbc2345fbc
  patches:
    - 0001-py38_windows.patch

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - epicscorelibs =7.0.3.99.4
    - numpy
    - pip
    - ply
    - setuptools
    - setuptools_dso
  run:
    - python
    - cython
    - epicscorelibs =7.0.3.99.4
    - nose >=1.1.2
    - {{ pin_compatible('numpy') }}
    - ply

test:
  imports:
    - p4p

about:
  home: http://github.com/mdavidsaver/p4p
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings for the PVAccess network client and server.
  doc_url: https://mdavidsaver.github.io/p4p/
  dev_url: https://github.com/mdavidsaver/p4p

extra:
  recipe-maintainers:
    - hhslepicka
