{% set name = "p4p" %}
{% set version = "3.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdavidsaver/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4b4a920e28163dc35977f5391ae82b475b7ddf0ee8ab5e05e61669ae3328609e
  patches:
    - 0001-py38_windows.patch

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - epicscorelibis =7.0.3.99.4
    - numpy
    - pip
    - ply
    - setuptools
    - setuptools_dso
  run:
    - python
    - cython
    - epicscorelibs =7.0.3.99.4
    - {{ pin_compatible('numpy') }}
    - ply

test:
  imports:
    - p4p

about:
  home: http://github.com/mdavidsaver/p4p
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python bindings for the PVAccess network client and server.'
  doc_url: https://mdavidsaver.github.io/p4p/
  dev_url: https://github.com/mdavidsaver/p4p

extra:
  recipe-maintainers:
    - hhslepicka
