{% set name = "p4p" %}
{% set version = "3.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdavidsaver/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 314915d79a8f0a96988aa59af70476fddfc127ca978739f33c287db201aaf07d
  patches:
    - 0001-py38_windows.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - epicscorelibs
    - numpy
    - pip
    - setuptools
    - setuptools_dso
  run:
    - python
    - epicscorelibs
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - p4p 

about:
  home: http://github.com/mdavidsaver/p4p
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python bindings for the PVAccess network client and server.'
  doc_url: https://mdavidsaver.github.io/p4p/
  dev_url: https://github.com/mdavidsaver/p4p

extra:
  recipe-maintainers:
    - hhslepicka
