travis:
  secure:
    BINSTAR_TOKEN: PI9qkH0SbcS6819oZ6GreopGvbQ3v0B0InB/LoTj3Wgv658w17PFT+eLhECF2Kdfr6Pmj5fcf+zQHy2XLfL1Fd76lDw9Rgb2FBtousldlD0oyUdBRyQsSfiUGyFI/BCumUaiW9mOnm4dwEBnVyjMGSkoXQCfOd8gpYoQTOP8V/lNK19LTaGzyYdTeHEaAsrLSTv6krXbrYC8wRy9io4XzecTjcMa0ZoKNTfXmQlpsWKzCGQTM9AZKuj7dPwbDuqygSnyE04J3rr7AeOKLws01Ha24aZRnZH+vVYm1FktiGApGHlC6cDrqi9lgoSQIP4rF69K6Srrml6kzqUwAGjkLPX63YkV+S2N8AF4Chq1EB5m0AIwErCtXpGU7LVoEro9pa+MvEjcDMhs8h9RN5gY10jLK1NTdjfeaBNzBnPXhcGIYJW181YfuxcDJjRgGxpvCBL0RfwhidOq25NlMLV6km8ENl6DE/PDIa/4LFndtUDDG7ErR/yzL518hzG1mAPMmXufw9NgnOD8aIKGEphqtgweqfLjF2vY8akbNFs5BL8bhPbdXaNiyrOs9gDoBQD68yUCBU0slEzymczCKCDMqtNaCckNfSAZwv5gOtNEcRZ89YWpMAfkd8kIklY3zeau68hAVPSYY/21hiQVD/gdYH4HL28+Rx8d5DDmVuQhTzA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
